cart/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

app_name='cart'

urlpatterns = [
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:product_id>/',views.cart_add,name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),

]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myshop/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',include('cart.urls',namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('',include('shop.urls',namespace='shop')),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
]
urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


shop/urls.py
from django.urls import path
from . import views 


app_name='shop'

urlpatterns = [
     path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, 
         name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail,
         name='product_detail'),
]

shop/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

# Create your models here.
class UserIpStore(models.Model):
    userip=models.CharField(max_length=200)
    countryname=models.CharField(max_length=200)
    regionname=models.CharField(max_length=200)
    city=models.CharField(max_length=200)
    latitude=models.CharField(max_length=200)
    longitude=models.CharField(max_length=200)
    def __str__(self):
        return "{} {} {} {}".format(self.userip , self.city , self.regionname, self.countryname)
    
class Category(models.Model):
    name=models.CharField(max_length=200,
                            db_index=True)
    slug=models.SlugField(max_length=200,
                            unique=True) 

    class Meta:
        ordering=('name',)
        verbose_name ='category'
        verbose_name_plural='categories'                                              

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])

class Product(models.Model):
    Category=models.ForeignKey(Category,on_delete=models.CASCADE,related_name='products')
    name=models.CharField(max_length=200,db_index=True)
    slug=models.SlugField(max_length=200,unique=True)
    image=models.ImageField(upload_to='prodcuts/%Y/%m/%d',blank=True)
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        ordering=('name',)
        index_together=(('id','slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',args=[self.id, self.slug])


shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product,UserIpStore
from cart.forms import CartAddProductForm
import requests
from decouple import config

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    ipstackapikey=config('IPSTACKAPI')
    googlemapapikey=config('GOOGLEMAPAPIKEY')
    useripaddress=request.META.get('HTTP_X_FORWARDED_FOR', '')
    print("------------------  dsdkkdksffj sdf --------",useripaddress)
    # response = requests.get('http://api.ipstack.com/{}?access_key={}'.format(useripaddress,ipstackapikey))
    # geodata=response.json()
    # userip=geodata['ip']
    # countryname=geodata['country_name'] 
    # regionname=geodata['region_name']
    # city=geodata['city'] 
    # latitude=geodata['latitude'] 
    # longitude=geodata['longitude']
    # print(geodata) 
    # UserIpStore.objects.create(userip=userip,countryname=countryname,regionname=regionname, city=city,latitude=latitude,longitude=longitude)
    # print("List -------------------------",request.META.get('HTTP_X_FORWARDED_FOR', ''),userip)

    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(Category__slug=category)
    return render(request, 'shop/product/list.html', {'cate gory': category, 'categories': categories, 'products': products})
    # 'latitude':latitude,'longitude':longitude,'mapapikey':googlemapapikey

def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form})

shop/templates/shop/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
 
    <title>{% block title %}My Shop{% endblock %}</title>
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>
<body>
    
    <!-- div for header -->
    <div id="header">
        <a href="/" class="logo">My Shop</a>
    </div>

    <!-- div for subheader -->
    <div id="subheader">
        <div class="cart">
             {% with total_items=cart|length %}
                {% if cart|length > 0 %}
                    Your Cart:&nbsp 
                    <a href="{% url 'cart:cart_detail' %}">
                        {{total_items}} Item{{total_items|pluralize}}&nbsp
                        Rs {{ cart.get_total_price }}
                    </a>
                {% else %}
                    Your Cart is empty
                {% endif %}
             {% endwith %}   
        </div>
    </div>

    <!-- div for content -->
    <div id='content'>
        {% block content %}
        {% endblock %}
    </div>

            <div class="copyright-main" style="position: fixed;
            left: 0;
            bottom: 10px;
            height:8%;
            width: 100%;
            background-color: #5993bb;
            color: white;
            text-align: center">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <h6 class="copy-title" style="font-size:14px">©2019 , All Right Reserved & developed by <a style="color: black" href="https://github.com/amitkadivar1/OnlineShop" target="_blank">Amit Kadivar</a> </h6>
                            {% block footer %}
                            {% endblock %}
                        </div>
                    </div>
                    <!-- end row -->
                </div>
                <!-- end container -->
            </div>

    
</body>
</html>